### ISSUE TITLE
libopencm3 and libopencm3-template have different PREFIX syntax

### ISSUE THREAD

**Issue by l29ah** [libopencm3/libopencm3-template#7]
The former appends `-` to the end of it, the latter doesn't.

**Comment by karlp** [comment]
yeah, I _feel_ that the -template repo is closer to what other projects do, which is why I did it.  Is this causing you some sort of problem?  are you using a toolchain that has a different prefix?

fwiw, searching github for $(PREFIX)gcc returns 13million results, while $(PREFIX)-gcc is only 177k results.

**Comment by karlp** [comment]
(so.... short of further discussion, this is more of a "bug" in violation of least surprise in the library itself, rather than here in the -template repo)

**Comment by l29ah** [comment]
The only problem is that i have to supply different PREFIX for making the project and the libopencm3.

**Comment by karlp** [comment]
hrm, I see that when using the submodule I guess.  still I'm more likely to fix it in the main library.  What PREFIX are you using anyway? I'm still curious what toolchain you're using that isn't arm-none-eabi

**Comment by l29ah** [comment]
`arm-bare_newlib_cortex_m3_nommu-eabi-`, as produced by `crosstool-ng`.

**Comment by karlp** [comment]
We'll fix this properly in the library, but I don't have time to do it myself right now. thanks for the report.
